const LOGIN_INPUT = 'LOGIN_INPUT';
const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
const REGISTER_INPUT = 'REGISTER_INPUT';
const REGISTER_SUBMIT = 'REGISTER_SUBMIT';

export {
    LOGIN_INPUT,
    LOGIN_SUBMIT,
    REGISTER_INPUT,
    REGISTER_SUBMIT,
};
